export const REGISTER_USER = "REGISTER_USER";

export const AUTH_USER = "AUTH_USER";
export const AUTH_USER_SUCCEEDED = "AUTH_USER_SUCCEEDED";
export const AUTH_USER_FAILED = "AUTH_USER_FAILED";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_LOGOUT_SUCCEEDED = "USER_LOGOUT_SUCCEEDED";
export const USER_LOGOUT_FAILED = "USER_LOGOUT_FAILED";
